# Generated by Django 3.0.1 on 2019-12-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='https://github.com/rousbound', max_length=30),
            preserve_default=False,
        ),
    ]
