  version: '3.9'

  services:
    application:
      image: "rousbound/cgilua:latest"
      tty: true
      container_name: "atelievirtual"
      hostname: "atelievirtual"
      volumes:
        - "/home/geraldo/Dropbox/C贸digo/Projects/atelievirtual/src:/home/app/src"
        - "/home/geraldo/Dropbox/C贸digo/Projects/atelievirtual/logs:/home/app/logs"
        - "/home/geraldo/Dropbox/C贸digo/Projects/atelievirtual/backup:/home/app/backup"
        - "/home/geraldo/Dropbox/C贸digo/Projects/atelievirtual/luarocks:/home/app/.luarocks"
      ports: 
        - "80:80"
        - "2222:22"
    # db:
    #   image: "postgres-cgilua:14"
    #   restart: always
    #   container_name: "atelievirtual-db"
