# Generated by Django 3.0.2 on 2020-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
