# Generated by Django 3.0.5 on 2020-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerj', '0002_auto_20200823_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pl',
            name='localdata',
            field=models.CharField(default='Governador', max_length=128),
        ),
    ]
